### ISSUE TITLE
Custom maps

### ISSUE THREAD

**Issue by bashbers** [sebdanielsson/docker-etlegacy#1]
How do I mount custom maps inside this docker image?
Whenever I mount /etmain, it overwrites everything from the base docker image.

**Comment by sebdanielsson** [comment]
Yes, if using bind mounts Docker will overwrite the directories in the Docker image with the the files from the host. You could copy the files from the volume to the etmain folder on your host and also add your custom maps to that folder.

On most distros you can find your Docker volumes at /var/lib/docker/volumes/xxx/_data/etmain
