### ISSUE TITLE
Issue launching docker image

### ISSUE THREAD

**Issue by cyrusdg** [sebdanielsson/docker-etlegacy#2]
Disclaimer: I'm somewhat of a docker n00b, but your help is greatly appreciated!!

Launching the docker image and mounted the package and config files and getting errors/crashing.

![image](https://user-images.githubusercontent.com/1441715/147706987-1d522e08-c645-45c2-8a87-410932fce6ab.png)

Here's the error log I'm getting:

![image](https://user-images.githubusercontent.com/1441715/147707013-7c3b6766-3a7b-4004-b074-4b7ce6d44418.png)

**Comment by sebdanielsson** [comment]
Try `/etlegacy/etmain` as your mount path☺️
